services:
  ecosensor-osm2pgsql:
      container_name: ecosensor-osm2pgsql
      image: ghcr.io/emp-projects/docker-osm2pgsql:main
      command: ./entrypoint.sh ${POSTGRES_HOST} ${POSTGRES_PORT} ${POSTGRES_OSM_USER} ${POSTGRES_OSM_PASS} ${POSTGRES_OSM_DB}
      restart: always
      environment:
        PGHOST: ${POSTGRES_HOST}
        PGDATABASE: ${POSTGRES_OSM_DB}
        PGUSER: ${POSTGRES_OSM_USER}
        PGPASSWORD: ${POSTGRES_OSM_PASS}
        PGPORT: ${POSTGRES_PORT}
      volumes:
        - ./osm:/osm
      networks:
        - ecosensor-network

  ecosensor-istat-ogr2ogr:
    container_name: ecosensor-istat-import
    image: ghcr.io/emp-projects/docker-istat:main
    command: ["./scripts/import.sh", "${POSTGRES_HOST}", "${POSTGRES_PORT}", "${POSTGRES_ISTAT_USER}", "${POSTGRES_ISTAT_PASS}", "${POSTGRES_ISTAT_DB}"]
    environment:
        PGPORT: ${POSTGRES_PORT}
        PGHOST: ${POSTGRES_HOST}
        PGDB: ${POSTGRES_ISTAT_DB}
        PGUSER: ${POSTGRES_ISTAT_USER}
        PGPWD: ${POSTGRES_ISTAT_PASS}
    networks:
        - ecosensor-network

  ecosensor-backend:
    container_name: ecosensor-backend
    image: ghcr.io/emp-projects/ecosensor:master
    restart: always
    environment:
      POSTGRES_OSM_HOST: ${POSTGRES_HOST}
      POSTGRES_OSM_DB: ${POSTGRES_OSM_DB}
      POSTGRES_OSM_USER: ${POSTGRES_OSM_USER}
      POSTGRES_OSM_PASS: ${POSTGRES_OSM_PASS}
      POSTGRES_OSM_PORT: ${POSTGRES_PORT}
      ECOSENSOR_OPENMETEO_API: ${ECOSENSOR_OPENMETEO_API}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_TOPIC_ARN: ${AWS_TOPIC_ARN}
      POSTGRES_ISTAT_HOST: ${POSTGRES_HOST}
      POSTGRES_ISTAT_PORT: ${POSTGRES_PORT}
      POSTGRES_ISTAT_DB: ${POSTGRES_ISTAT_DB}
      POSTGRES_ISTAT_USER: ${POSTGRES_ISTAT_USER}
      POSTGRES_ISTAT_PASS: ${POSTGRES_ISTAT_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${ECOSENSOR_PORT}:80
    networks:
      - ecosensor-network

networks:
  ecosensor-network:
    name: ecosensor
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24

volumes:
  db:
    driver: local
