services:
  
  ecosensor-backend:
    container_name: ecosensor-backend
    image: ghcr.io/emp-projects/ecosensor:master
    profiles: ["all"]
    restart: always
    environment:
      POSTGRES_HOST: ecosensor-db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_PORT: 5432
      OPENMETEO_API: ${OPENMETEO_API}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_TOPIC_ARN: ${AWS_TOPIC_ARN}
    ports:
      - ${ECOSENSOR_PORT}:80
    depends_on:
      ecosensor-db:
        condition: service_healthy
    networks:
      - ecosensor-network